disabled_rules:
  - trailing_whitespace
  - colon
  - line_length
  - function_parameter_count
  - syntactic_sugar
  - function_body_length
  - file_length
  - multiple_closures_with_trailing_closure
  - identifier_name
  - cyclomatic_complexity
  - private_over_fileprivate
  - void_return
  - class_delegate_protocol
  - block_based_kvo
  - weak_delegate

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

identifier_name:
  min_length: # only min_length
    warning: 1
  excluded: # excluded via string array
    - id
